// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * static boolean 	equals(String filename1, String filename2)
 * Determines whether the parent directory contains the child element (a file or directory).
 */
public class filenameutils_equals extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String filename1;
	private java.lang.String filename2;

	public filenameutils_equals(IContext context, java.lang.String filename1, java.lang.String filename2)
	{
		super(context);
		this.filename1 = filename1;
		this.filename2 = filename2;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return org.apache.commons.io.FilenameUtils.equals(filename1,filename2);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_equals";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
