// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 *     //          Checks whether the extension of the filename is one of those specified.
    //static boolean 	isExtension(String filename, String extension)

 */
public class filenameutils_isExtension extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String filename;
	private java.lang.String extension;

	public filenameutils_isExtension(IContext context, java.lang.String filename, java.lang.String extension)
	{
		super(context);
		this.filename = filename;
		this.extension = extension;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return org.apache.commons.io.FilenameUtils.isExtension(filename,extension);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_isExtension";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
