// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 *     //          Normalizes a path, removing double and single dot path steps.
    //static String 	normalize(String filename, boolean unixSeparator)

 */
public class filenameutils_normalize extends CustomJavaAction<java.lang.String>
{
	private java.lang.String filename;
	private java.lang.Boolean unixSeparator;

	public filenameutils_normalize(IContext context, java.lang.String filename, java.lang.Boolean unixSeparator)
	{
		super(context);
		this.filename = filename;
		this.unixSeparator = unixSeparator;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return org.apache.commons.io.FilenameUtils.normalize(filename,unixSeparator);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_normalize";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
