// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * static int 	indexOfExtension(String filename)
 * Returns the length of the filename prefix, such as C:/ or ~/.
 */
public class filenameutils_indexOfExtension extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String filename;

	public filenameutils_indexOfExtension(IContext context, java.lang.String filename)
	{
		super(context);
		this.filename = filename;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new java.lang.Long(org.apache.commons.io.FilenameUtils.indexOfExtension(filename));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_indexOfExtension";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
