// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 *     //          Converts all separators to the system separator.
    //static String 	separatorsToUnix(String path)

 */
public class filenameutils_separatorsToUnix extends CustomJavaAction<java.lang.String>
{
	private java.lang.String path;

	public filenameutils_separatorsToUnix(IContext context, java.lang.String path)
	{
		super(context);
		this.path = path;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return org.apache.commons.io.FilenameUtils.separatorsToUnix(path);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_separatorsToUnix";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
