// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 *     //          Returns the index of the last extension separator character, which is a dot.
    //static int 	indexOfLastSeparator(String filename)

 */
public class filenameutils_indexOfLastSeparator extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String filename;

	public filenameutils_indexOfLastSeparator(IContext context, java.lang.String filename)
	{
		super(context);
		this.filename = filename;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new java.lang.Long(org.apache.commons.io.FilenameUtils.indexOfLastSeparator(filename));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_indexOfLastSeparator";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
