// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 *     //          Checks a filename to see if it matches the specified wildcard matcher, always testing case-sensitive.
    //static boolean 	wildcardMatch(String filename, String wildcardMatcher, IOCase caseSensitivity)

 */
public class filenameutils_wildcardMatch extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String filename;
	private java.lang.String wildcardMatcher;
	private java.lang.String caseSensitivity;

	public filenameutils_wildcardMatch(IContext context, java.lang.String filename, java.lang.String wildcardMatcher, java.lang.String caseSensitivity)
	{
		super(context);
		this.filename = filename;
		this.wildcardMatcher = wildcardMatcher;
		this.caseSensitivity = caseSensitivity;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "filenameutils_wildcardMatch";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
