// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_delim2xlsx extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_content;
	private java.lang.String str_delim;
	private IMendixObject __obj_filedocument;
	private system.proxies.FileDocument obj_filedocument;

	public ja_delim2xlsx(IContext context, java.lang.String str_content, java.lang.String str_delim, IMendixObject obj_filedocument)
	{
		super(context);
		this.str_content = str_content;
		this.str_delim = str_delim;
		this.__obj_filedocument = obj_filedocument;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.obj_filedocument = __obj_filedocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __obj_filedocument);

		// BEGIN USER CODE
		java.lang.Boolean ret=true;
		if(obj_filedocument==null){
			throw new Exception("FileDocument null");
		}else if(str_content==null){
			throw new Exception("Content null");
		}else{
			java.lang.String _str_delim=str_delim==null?",":str_delim;
			java.util.List<java.util.List<java.lang.String>> records = new java.util.ArrayList<>();
			java.lang.String COMMA_DELIMITER=_str_delim;
			try{
				com.mendix.modules.exportmanager.interfaces.excel.IExcelGrid grd=com.mendix.modules.exportmanager.ExportManagerModule.createExcelGrid();
				java.io.BufferedReader br=new java.io.BufferedReader(new java.io.StringReader(str_content));
				java.lang.String line;
				while((line=br.readLine())!=null) {
					java.lang.String[] values=line.split(COMMA_DELIMITER);
					records.add(java.util.Arrays.asList(values));
				}
				for(int ridx=0;ridx<records.size();ridx++){
					try{
						for(int colidx=0;colidx<records.get(ridx).size();colidx++){
							grd.getColumn(colidx).getCell(ridx).setContent(records.get(ridx).get(colidx));
						}
					}catch(Exception e){
						com.mendix.core.Core.getLogger(this.toString()).error(e);
					}
				}
				com.mendix.modules.exportmanager.ExportManagerModule.generateXLS(
					this.getContext(),
					obj_filedocument.getMendixObject(),
					obj_filedocument.getMendixObject().getValue(this.getContext(),"Name"),
					grd
				);
				return true;
			}catch(Exception e){
				throw new Exception(e);
			}
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_delim2xlsx";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
