// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * delete file from disk
 */
public class ja_File_delete extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_path;

	public ja_File_delete(IContext context, java.lang.String str_path)
	{
		super(context);
		this.str_path = str_path;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		boolean ret=true;
		java.io.File file = new java.io.File(str_path); 
		if(file.delete()){
			com.mendix.core.Core.getLogger(this.toString()).info("File deleted successfully"); 
		}else{
			com.mendix.core.Core.getLogger(this.toString()).error("File not deleted"); 
			ret=false;
		} 
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_File_delete";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
