// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ja_strcsv2arrmxobj extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_objtyp;
	private java.lang.String str_varnam;
	private java.lang.String str_csv;
	private java.lang.String str_delimiter;

	public ja_strcsv2arrmxobj(IContext context, java.lang.String str_objtyp, java.lang.String str_varnam, java.lang.String str_csv, java.lang.String str_delimiter)
	{
		super(context);
		this.str_objtyp = str_objtyp;
		this.str_varnam = str_varnam;
		this.str_csv = str_csv;
		this.str_delimiter = str_delimiter;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<java.util.List<java.lang.String>> records = new java.util.ArrayList<>();
		java.lang.String COMMA_DELIMITER=str_delimiter;//",";
		java.util.Stack<com.mendix.core.actionmanagement.CoreAction<?>> astack=getContext().getActionStack();
		try{
			java.io.BufferedReader br=new java.io.BufferedReader(new java.io.StringReader(str_csv));
			java.lang.String line;
			while((line=br.readLine())!=null) {
				java.lang.String[] values=line.split(COMMA_DELIMITER);
				records.add(java.util.Arrays.asList(values));
			}
			for(int ridx=1;ridx<records.size();ridx++){
				try{
					com.mendix.systemwideinterfaces.core.IMendixObject obj=com.mendix.core.Core.instantiate(
						this.getContext(),
						str_objtyp
					);
					for(int hdridx=0;hdridx<records.get(0).size();hdridx++){
						try{
							obj.setValue(
								this.getContext(),
								records.get(0).get(hdridx),
								records.get(ridx).get(hdridx)
							);
						}catch(Exception e){
							com.mendix.core.Core.getLogger(this.toString()).error(e);
						}
					}
					java.lang.reflect.Method method;
					try{
						method = astack.get(2).getClass().getMethod("getVariable",java.lang.String.class);
						try{
							java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> lst=(java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject> )method.invoke(astack.get(2),str_varnam);//, arg1, arg2,...);
							lst.add(obj);
						}catch(Exception e){com.mendix.core.Core.getLogger(this.toString()).error(e);}
					}catch (Exception e) {com.mendix.core.Core.getLogger(this.toString()).error(e);}
					//lst.add(obj);
				}catch(Exception e){
					com.mendix.core.Core.getLogger(this.toString()).error(e);
				}
			}
			return true;
		}catch(Exception e){
			com.mendix.core.Core.getLogger(this.toString()).error(e);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_strcsv2arrmxobj";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
