// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * set file permissions
 * java.nio.file.Files.setPosixFilePermissions(new File(str_pth).toPath(),java.nio.file.attribute.PosixFilePermissions.fromString("rwxr-x---"));

 */
public class ja_setPosixFilePermissions extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_pth;
	private java.lang.String str_perm;

	public ja_setPosixFilePermissions(IContext context, java.lang.String str_pth, java.lang.String str_perm)
	{
		super(context);
		this.str_pth = str_pth;
		this.str_perm = str_perm;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		/*
		try{
			java.nio.file.Files.setPosixFilePermissions(
					new java.io.File(str_pth),
					java.nio.file.attribute.PosixFilePermissions.fromString(
						str_perm
					)
			);
		}catch(Exception e){
			com.mendix.core.Core.getLogger(this.toString()).error(e);
			throw e;
		}
		*/
		this.setFilePerm(new java.io.File(str_pth),str_perm);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_setPosixFilePermissions";
	}

	// BEGIN EXTRA CODE
	public static void setFilePerm(java.io.File file, java.lang.String perm) {
		try {
			java.util.Set<java.nio.file.attribute.PosixFilePermission> perms = java.nio.file.attribute.PosixFilePermissions.fromString(perm);
			java.nio.file.attribute.PosixFileAttributes attr = java.nio.file.Files.readAttributes(file.toPath(), java.nio.file.attribute.PosixFileAttributes.class);
			attr.permissions().clear();
			java.nio.file.Files.setPosixFilePermissions(file.toPath(), perms);
		} catch (java.io.IOException e) {
			throw new java.lang.IllegalStateException(e);
		}
	}
	// END EXTRA CODE
}
