// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * get number of lines in string with line seperators \r\n or \n
 */
public class ja_strlinecount extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String v;

	public ja_strlinecount(IContext context, java.lang.String v)
	{
		super(context);
		this.v = v;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new Long(this.countLines(v));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_strlinecount";
	}

	// BEGIN EXTRA CODE
	private int countLines(java.lang.String str){
		java.lang.String[] lines = str.split("\r\n|\r|\n");
		return  lines.length;
	}
	// END EXTRA CODE
}
