// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import java.io.*;
import javax.xml.transform.*;
import javax.xml.transform.stream.*;
import java.util.Scanner;
import java.io.InputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.BufferedInputStream;

/**
 * rudimentary xml prettifier
 * 
 * todo:
 *     convert this to a json of kv's to pass into the action
 *            transformer.setOutputProperty(
 * k->            "{http://xml.apache.org/xslt}indent-amount",
 * v->            "2"
 *            );
 * 
 */
public class ja_xmlprettify extends CustomJavaAction<java.lang.String>
{
	private java.lang.String str_xml;
	private java.lang.Long int_identamt;

	public ja_xmlprettify(IContext context, java.lang.String str_xml, java.lang.Long int_identamt)
	{
		super(context);
		this.str_xml = str_xml;
		this.int_identamt = int_identamt;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String str_retval=new String();
		this._int_identamt=int_identamt==null?2:int_identamt.intValue();
		try{
			Source xmlInput=new StreamSource(
				new StringReader(
					str_xml
				)
			);
			StreamResult xmlOutput=new StreamResult(
				new StringWriter()
			);
			Transformer transformer=TransformerFactory.newInstance().newTransformer();
			transformer.setOutputProperty(
				OutputKeys.DOCTYPE_SYSTEM,
				"testing.dtd"
			);
			transformer.setOutputProperty(
				OutputKeys.INDENT,
				"yes"
			);
			//todo: convert this to a json of kv's to pass into the action
			transformer.setOutputProperty(
				"{http://xml.apache.org/xslt}indent-amount",
				//new java.lang.String(
				//	this._int_identamt
				//)
				"2"
			);
			transformer.transform(
				xmlInput,
				xmlOutput
			);
			str_retval=xmlOutput.getWriter().toString();
		}catch(Exception e){
			Core.getLogger(this.toString()).error(e.toString());
			throw e;
		}
		return str_retval;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_xmlprettify";
	}

	// BEGIN EXTRA CODE
	int _int_identamt;
	// END EXTRA CODE
}
