// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * returns list of MxUtil.KV with K populated to all mxutil.Schedule.hashmap K
 * 
 */
public class tpts_list extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public tpts_list(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> r=new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
		java.util.Iterator<java.util.Map.Entry<java.lang.String,java.util.concurrent.ExecutorService>> it=mxutil.Schedule.hashmap.entrySet().iterator();
		while(
			it.hasNext()
		){
			java.util.Map.Entry<java.lang.String,java.util.concurrent.ExecutorService>pair=(java.util.Map.Entry<java.lang.String,java.util.concurrent.ExecutorService>)it.next();
			com.mendix.systemwideinterfaces.core.IMendixObject o=com.mendix.core.Core.instantiate(
				this.getContext(),
				"MxUtil.KV"
			);
			try{
				o.setValue(this.getContext(),"K",pair.getKey());
				//todo: v
			}catch(Exception e){
				com.mendix.core.Core.getLogger(this.toString()).error(e);
			}
			r.add(o);
		}
		return r;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "tpts_list";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
