// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class tpts_del extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String tptsid;

	public tpts_del(IContext context, java.lang.String tptsid)
	{
		super(context);
		this.tptsid = tptsid;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		//todo: ensure disposal
		java.lang.Boolean r=false;
		if(tptsid!=null){
			java.util.concurrent.ExecutorService es=mxutil.Schedule.hashmap.get(tptsid);
			if(es!=null){
				try{
					es.shutdown();
					mxutil.Schedule.hashmap.remove(tptsid);
					r=true;
				}catch(Exception e){
					com.mendix.core.Core.getLogger(this.toString()).error(e.toString());
					r=false;
				}
			}else{
				mxutil.Schedule.hashmap.remove(tptsid);
				r=false;
				com.mendix.core.Core.getLogger(this.toString()).error(tptsid+" not found, removed");
			}
		}else{
			com.mendix.core.Core.getLogger(this.toString()).error(tptsid+" null");
			r=false;
		}
		return r;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "tpts_del";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
